#!/usr/bin/env python3
"""Room-by-room acceptance table (spec 12) from plan.json and staging.json, written to notes/acceptance.md.

Columns: geometry (room in the plan with its parts), openings (doors/windows touching the room), finishes (floor, wall,
ceiling materials resolve), furniture (staging entries in the room), lighting (entries that register a light), objects
(small props and models). A cell is "pass" when the count is at least what the spec calls for, "n/a" for rooms the spec
leaves bare, else "FAIL".

    python3 tools/acceptance.py
"""
import json
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
LIGHT_GENS = {"downlight", "downlights", "sconce", "picture_light", "floor_lamp", "pendant_cone", "led_strip", "shop_light",
              "globe_pendant", "pendant_row", "three_globe_pendant", "sputnik", "table_lamp", "arc_lamp", "mushroom_lamp",
              "desk_lamp", "task_lamp", "linear_fire", "vanity2", "kitchen2", "bar2", "sauna2", "rack", "tv_wall",
              "ext_sconce", "soffit_downlight", "heater", "nightstand2", "console", "watch_island", "wardrobe", "workbench",
              "hearth_bench", "fridge_small", "charger", "desk"}
BARE = {"elevator_closet", "elevator_closet2", "battery", "panel_closet", "litter_closet", "coat_closet", "stair_well", "closet_a", "closet_b", "linen",
        "bstair_hall", "hall_south", "work_corridor", "suite_hall", "up_laundry", "storage", "mechanical", "gear_closet"}


def touches(room, op):
    for p in room["parts"]:
        x0, y0, x1, y1 = p
        if op["axis"] == "x" and (abs(op["at"] - y0) < 1e-6 or abs(op["at"] - y1) < 1e-6):
            lo, hi = op["c"] - op["w"] / 2, op["c"] + op["w"] / 2
            if lo < x1 - 1e-6 and hi > x0 + 1e-6:
                return True
        if op["axis"] == "y" and (abs(op["at"] - x0) < 1e-6 or abs(op["at"] - x1) < 1e-6):
            lo, hi = op["c"] - op["w"] / 2, op["c"] + op["w"] / 2
            if lo < y1 - 1e-6 and hi > y0 + 1e-6:
                return True
    return False


def main():
    plan = json.load(open(os.path.join(ROOT, "plan.json")))
    staging = json.load(open(os.path.join(ROOT, "staging.json")))
    mats = json.load(open(os.path.join(ROOT, plan["materials_file"])))
    rows = []
    for r in plan["rooms"]:
        nm = r["name"]
        ops = [o for o in plan["openings"] if o["floor"] == r["floor"] and touches(r, o)]
        fin = all(m in mats for m in (r["floorm"], r["wall"], r["ceil"]))
        ents = [e for e in staging if e.get("room") == nm and "asset" in e]
        procs = [e["asset"][5:] for e in ents if e["asset"].startswith("proc:")]
        models = [e for e in ents if not e["asset"].startswith("proc:")]
        lights = [g for g in procs if g in LIGHT_GENS]
        furniture = [g for g in procs if g not in ("downlight", "downlights", "wall_finish", "rug", "runner", "roller_shade")]
        bare = nm in BARE

        def cell(ok, count=None):
            if ok:
                return "pass (%d)" % count if count is not None else "pass"
            return "n/a" if bare else "FAIL"
        rows.append((nm, r["floor"], "pass" if r["parts"] else "FAIL", cell(len(ops) > 0, len(ops)), "pass" if fin else "FAIL",
                     cell(len(furniture) > 0, len(furniture)), cell(len(lights) > 0, len(lights)), cell(len(models) + len(procs) > 0, len(models) + len(procs))))
    out = ["# Room-by-room acceptance (spec 12)", "",
           "Generated by tools/acceptance.py from plan.json and staging.json. Counts in brackets: openings touching the room,",
           "furniture generators, light-emitting entries, all staged entries (models + procedural).", "",
           "| room | floor | geometry | openings | finishes | furniture | lighting | objects |", "|---|---|---|---|---|---|---|---|"]
    for row in rows:
        out.append("| " + " | ".join(row) + " |")
    site_rows = [("porch", "porch_bench, ceiling_fan, ext_sconce, house_numbers, mail_slot, soffit downlights"),
                 ("breezeway", "roof, posts, slat screen, bluestone walk (site_build)"),
                 ("terrace", "canopy, grill, heaters, table set, planters, swim spa with open cover, catio frame (site_build + staging)"),
                 ("lawn and beds", "leafy lawn, gravel bands, beds with mounds, hedges, trees (site_build + neighborhood)"),
                 ("street and neighbors", "street, curbs, parkways, sidewalks, lamps, hydrant, 25 neighbours, alley garages (neighborhood)")]
    out += ["", "| site item | what exists |", "|---|---|"] + ["| %s | %s |" % s for s in site_rows]
    fails = sum(1 for row in rows for c in row[2:] if c == "FAIL")
    out += ["", "FAIL cells: %d. Cats: omitted (no CC0 model; spec 11.4)." % fails]
    open(os.path.join(ROOT, "notes", "acceptance.md"), "w").write("\n".join(out) + "\n")
    print("rooms", len(rows), "FAIL cells", fails)
    for row in rows:
        if "FAIL" in row:
            print("  ", row)


if __name__ == "__main__":
    main()
